<a href="https://colab.research.google.com/github/JuanCamilo0101/MetNumUN2023I/blob/main/Quiz_1_Python_NumPy_UNCode/Juplazasp_Quiz_1_Python_NumPy_UNCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Quiz 1 - Python NumPy**
---
This quiz will help you practice the skills coding in Python and using Numpy.

> **Note:** This aquiz will be graded on **UNCode** **[https://uncode.unal.edu.co/](https://uncode.unal.edu.co/)** ([doumentation](https://juezun.github.io/)). In each exercise is indicated where you should write your code. Complete the code, download the file submit it in **UNCode**.

In [15]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


This quiz was created originaly in:

- Python 3.6.9

- NumPy: 1.19.5

## **1. *FizzBuzz*  - Python**

---

###**Problem Description**

**Task:** Given an integer $x$ return:
 

*   The string "**`Fizz!`**" if $x$ is divisible by $3$ and not  divisible by $5$.
*    The string "**`Buzz!`**" if $x$ is divisible by $5$ and not  divisible by $3$.
*    The string "**`FizzBuzz!`**" if $x$ is divisible by both $5$ and divisible by $3$.
*    The string "**`...`**" otherwise.

**Input Format:** The input consists of a single integer $x$. 

**Constraints:** $x$ is an integer

**Output Format:**  the output is a string.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

FizzBuzz(3)

#  --> Expected output: Fizz!

FizzBuzz(11)

#  --> Expected output: ...

FizzBuzz(5)
#  --> Expected output: Buzz!

FizzBuzz(7)
#  --> Expected output:...

FizzBuzz(15)
#  --> Expected output: FizzBuzz!
```

---

**Solution**

In [16]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
    if x % 3 == 0 and x % 5 == 0:
        return "FizzBuzz!"
    elif x % 3 == 0:
        return "Fizz!"
    elif x % 5 == 0:
        return "Buzz!"
    else:
        return "..."


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>


In [17]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


Expected output:
``` 
Fizz!
...
Buzz!
...
FizzBuzz!
```

## **2. *FizzBuzzList*  - Python**
---

Write the function *FizzBuzzList* that returns a list with the answers of *FizzBuzz* for the integer numbers $1$ to $n$ (including $n$).

---

###**Problem Description**

**Task:** Given an integer $n$ return the list with the *FizzBuzz* answers for the integer numbers $1$ to $n$ (including $n$).
  

**Input Format:** The input consists of a single integer $n$. 

**Constraints:** $n$ is an integer

**Output Format:**  list with the *FizzBuzz* answers, if the input is not positive return an empty list.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

FizzBuzzList(4)
#  --> Expected output: ['...', '...', 'Fizz!', '...']
 
FizzBuzzList(-1)
#  --> Expected output: []
```
---

**Solution**

In [18]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    if n < 1:
        return []
    ans = []
    for i in range(1, n+1):
        if i % 3 == 0 and i % 5 == 0:
            ans.append("FizzBuzz!")
        elif i % 3 == 0:
            ans.append("Fizz!")
        elif i % 5 == 0:
            ans.append("Buzz!")
        else:
            ans.append("...")
    return ans

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>

In [19]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


Expected output:
``` 
['...', '...', 'Fizz!', '...', 'Buzz!']
[]
```

## **3. *Standarize* - z scores - NumPy**

---

###**Problem Description**

**Task:** Given an numpy array $X$ return the corresponding standard scores.
  
**Input Format:** The input consists of a numpy array $X$. 

**Output Format:**  A numpy array with standard scores corresponding to $X$.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

X0 = np.array([4.8, 4.0, 4.2, 4.0, 5.0])
standarize(X0)

#  --> Expected output: array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])

X1 = np.arange(5)
standarize(X1)

#  --> Expected output: array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

```
---

**Solution**

In [21]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = ((X - np.mean(X)) / np.std(X))
  return X_standarized

In [22]:
X0 = np.array([4.8, 4.0, 4.2, 4.0, 5.0])
standarize(X0)


array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])

In [23]:
X1 = np.arange(5)
standarize(X1)


array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

## **4. *Main diagonal matrix*  - NumPy**

---

###**Problem Description**

**Task:** Given a numpy matrix $A$ (2-D array) return the diagonal matrix with the elements of its main diagonal.
 

**Input Format:** The input consists of a numpy matrix $A$ (2-D array).

**Output Format:**  The diagonal matrix with the elemnts of its main diagonal.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])
main_diagonal_matrix(A)
#  --> Expected output: 
array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

A = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]
    
])
main_diagonal_matrix(A)
#  --> Expected output: 
array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])
```
---

In [26]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float)
  return D

In [33]:
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]

])
main_diagonal_matrix(A)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [28]:
A = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]

])
main_diagonal_matrix(A)

array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])